---
- name: "CI : {{ app_name }}"
  hosts: all
  become: false
  vars:
    app_name: peek-go
    app_repo_url: https://github.com/pumphouse-p/peek-go
    app_repo_branch: devel
    golang_version: 1.16.14
    golang_workspace: "{{ ansible_env.HOME }}/go/src"
    golang_app_workspace: "{{ golang_workspace }}/{{ app_name }}"
    container_base: buster
    container_image: "golang:{{ golang_version}}-{{ container_base }}"

  tasks:
    - name: Create workspace directory
      ansible.builtin.file:
        path: "{{ golang_workspace }}/go/src"
        state: directory
        mode: 0755

    - name: Clone repository
      ansible.builtin.git:
        repo: "{{ app_repo_url }}"
        version: "{{ app_repo_branch }}"
        dest: "{{ golang_app_workspace }}"

    - name: "Build : {{ app_name }}"
      containers.podman.podman_container:
        name: "{{ app_name }}-build"
        image: "{{ container_image }}"
        volume:
          - "{{ golang_app_workspace }}:/usr/src/{{ app_name }}:Z"
        workdir: /usr/src/{{ app_name }}/cmd/peek-go
        command: go build -v
        state: started
        interactive: true
        tty: true
        recreate: true
      register: build_container

    - name: "Run tests : {{ app_name }}"
      containers.podman.podman_container:
        name: "{{ app_name }}-test"
        image: "{{ container_image }}"
        volume:
          - "{{ golang_app_workspace }}:/usr/src/{{ app_name }}:Z"
        workdir: /usr/src/{{ app_name }}
        command: go test -v ./...
        state: started
        interactive: true
        tty: true
        recreate: true
      register: test_container
