---
app_name: peek-go
app_repo_url: https://github.com/pumphouse-p/peek-go
app_repo_refspec: "{{ tower_webhook_payload.ref | default(omit) }}"
app_repo_branch: master
golang_version: 1.16.14
golang_workspace: "{{ ansible_env.HOME }}/go/src"
golang_app_workspace: "{{ golang_workspace }}/{{ app_name }}"
build_container_base: buster
build_container_image: "golang:{{ golang_version}}-{{ build_container_base }}"
build_container_name: "{{ app_name }}-build"
test_container_name: "{{ app_name }}-test"
container_image_repo: quay.io/deparris/peek-go
